### PR TITLE
Add some locations statistics to the statistics tab

### PR DESCRIPTION
**Pull request by oparaskos**

### CODE REVIEW

**Comment by piersdeseilligny** [comment]
Hi @oparaskos and thanks for this! It's looking really good, although there's one breaking issue which is preventing me from merging it: something about the regex in parseLocationInformation seems broken and is causing an infinite loop, and I can't quite figure out what. I'il have a look at it when I have time, but in the meantime here's a demo of a string that breaks it: https://regexr.com/77qbr

**Comment by piersdeseilligny** [comment]
That's it mostly fixed (still a few things to iron out), however before merging it, one last thing I'd like to figure out and discuss is if the table should be moved into the "Scenes" section or not:
image

The argument against doing so is that "Scenes" and "Locations" are different concepts, in theory there could be 50 different scenes in just 2 locations. However, unless any more charts or information were to go in the "Locations" page, then might as well just include it in the "scenes" page especially given there's already all the "interior/exterior" information in there. Did you have any other charts or data in mind for the "Locations" page @oparaskos ?

**Comment by oparaskos** [comment]
> other charts or data in mind

I had in mind some vague ideas but I don't think i wrote them down.

Probably best to just shove it in with the scenes so that things stay tidy if/until someone comes up with something interesting to build on top of locations.

**Comment by piersdeseilligny** [comment]
Fair enough - my last few commits have also added chart highlighting on hover and fixed a couple bugs. If you're happy with it all then I think I'm happy to merge this by now :)

**Comment by oparaskos** [comment]
that looks good to me.

**Pull request merged**
