### PR TITLE
Added synchronized markup and preview setting and functionality

### PR DESCRIPTION
**Pull request by segreeeen**
A friend thought this feature would be helpful to him so I gave it a try. Please review and test.

### CODE REVIEW

**Comment by piersdeseilligny** [comment]
Thank you so much for this PR! I'il check it out in the next few days but it's looking good to merge as far as i can tell.

**Comment by piersdeseilligny** [comment]
@segreeeen so I've looked closer into how this works, and it's really great - however do you think it would be possible to avoid adding empty divs with the id "jumpToLine_n", but instead just set the ids of the elements which already absolutely have to be there? The DOM can already get quite large with a full-length screenplay...

For example, instead of generating the following (taken at random from the Pulp Fiction screenplay):
```html
<div class="dialogue">
   <div id="jumpToLine_43"></div>
   <h4>YOUNG WOMAN</h4>
   <div id="jumpToLine_44"></div>
   <p>You sound like a duck.</p>
   <div id="jumpToLine_45"></div>
   <p class="parenthetical">(imitates a duck)</p>
   <div id="jumpToLine_46"></div>
   <p>Quack, quack, quack, quack, quack, quack, quack...</p>
</div>
```

It would probably be more efficient to generate the following:

```html
<div class="dialogue">
   <h4 id="jumpToLine_43">YOUNG WOMAN</h4>
   <p id="jumpToLine_44">You sound like a duck.</p>
   <p id="jumpToLine_45" class="parenthetical">(imitates a duck)</p>
   <p id="jumpToLine_46">Quack, quack, quack, quack, quack, quack, quack...</p>
</div>
```


That said, if it worsens the performance of generating the HTML, it may not be worth it.

**Comment by segreeeen** [comment]
Hi,
as far as I remember, I made the choice to keep them as separate divs because some elements already had an id set for them, and I didn't want to break something so the fastest and less complicated way seemed to be to introduce the divs. I'll try to put the id's in the already existing tags. You are of course right. My div solution bloats the dom to double it's size...

**Comment by segreeeen** [comment]
You were right, it was easily possible to add the ids to the existing tags. Done ;).

**Comment by piersdeseilligny** [comment]
Amazing! That's cut down the size of the DOM from about 8000 elements (for Pulp Fiction's screenplay) to 4000. Thank you so much!

I'm going to try and add scroll-sync the other way around before merging this (so that scrolling the preview scrolls the editor). Although I can't work on it right now, so if you're bored these days let me know :D 

i think [this function](https://github.com/microsoft/vscode/blob/b10335675f9673cbd87e04d6a9808d3d6a75975a/extensions/markdown-language-features/preview-src/scroll-sync.ts#L72) from the markdown preview extension could help with this, as it uses a binary search to find the element at the top of the viewport in O(log n) rather than O(n)

**Comment by segreeeen** [comment]
I thought about this and came to the conclusion, that scrolling the editor is the only relevant thing to be synced - at least in my oppinion. That's why I didn't look at the other way round. I think that people are mainly interested in seeing the position where the cursor is at (which is also synchronized - i.e. if you klick in the textview).
Now of course I can look into the other way round, I still don't know if this is really relevant. I'll look at the link you posted and if it seems easy to implement I'll do it.

//edit: I took a look at the function you posted - if it's really possible to get the html element at some position, it might be realtively easy to also jump there in the texteditor... interesting ;).

**Comment by piersdeseilligny** [comment]
@segreeeen so i sort of hijacked this branch to completely overhaul the architecture of the previewing system, which now includes bidirectional scroll-sync, active line highlighting, jumping to a selection in the editor by double-clicking in the preview, persistent previews across vscode restarts, etc...

I'm going to merge it, and will release all these changes (and possibly a few more) as part of 1.6.0

**Comment by segreeeen** [comment]
Hell yeah, great job! I'm thrilled to try out the next release!

**Pull request merged**
