### PR TITLE
Statistics

### PR DESCRIPTION
**Pull request by rickschubert**
This pull request adds a new feature: statistics. A showcase video: https://recordit.co/qcxEYBNVgI

The statistics currently only include a few stats about the characters: which character speaks the most, how many words are they speaking, how many speaking parts do they have. Additionally, there is a basic metric listing the total scene numbers.

In the future, we could expand on those statistics, i.e. how many minutes each character speaks. Another metric I would find useful would be to show how many INT. vs. EXT. there are and whether there is one scene that occurs very often, i.e. "convenience store" in the movie "Clerks".

I have also added unit tests (`npm test` command). These unit tests are *not* running in the Visual Studio Code extension host. I have achieved so by using jest and mocking the vscode interface. That way, I was able to quickly verify my changes while I was developing.

### CODE REVIEW

**Comment by piersdeseilligny** [comment]
@rickschubert this looks amazing! I'm pretty occupied right now, but i'il check it out asap and merge it, along with the other pull requests

**Comment by rickschubert** [comment]
Thank you for the praise @piersdeseilligny I just wanted to say that I absolutely love your extension, I think it is by far the best free fountain text processing tool out there.

**Comment by rickschubert** [comment]
Any news on these pull requests @piersdeseilligny ? I would love to use them on my own script :)

**Comment by piersdeseilligny** [comment]
@rickschubert i'm sorry if i haven't had time to merge them, but I've been really occupied for the last few weeks and just haven't had time at all :/ I'il probably be able to deal with it soon after the 3rd of October, but in the meantime you could just create a .vsix with your local version (`vsce package` in the command line) and then install it to vscode via "Install from VSIX".

**Comment by rickschubert** [comment]
Thank you, I will check out how to generate this VSIX! I did find the option "Install from VSIX" but never knew how to generate it. In that case, no need to hurry at all. Thank you!

**Pull request merged**
