### PR TITLE
Run tests on every pull request

### PR DESCRIPTION
**Pull request by rickschubert**

### CODE REVIEW

**Comment by piersdeseilligny** [comment]
@rickschubert should this be merged?

**Comment by ricklondon** [comment]
What the pull request was about is working - it is always running the tests on pull requests and on the main branch. But it looks like a lot has changed with the statistics but the tests haven't been updated, therefore they are failing/don't compile yet. I think it would be best to amend the tests as well, otherwise there would be always failures.

**Comment by rickschubert** [comment]
What the pull request was about is working - it is always running the tests on pull requests and on the main branch. But it looks like a lot has changed with the statistics but the tests haven't been updated, therefore they are failing/don't compile yet. I think it would be best to amend the tests as well, otherwise there would be always failures.

**Comment by piersdeseilligny** [comment]
yep, the tests have also been broken by the [move from using the `vscode` npm package to using `@types/vscode` and `vscode-test`](https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest). I have to admit I'm not at all familiar with unit testing, so am not sure how to fix this.

**Comment by rickschubert** [comment]
I can have a look at fixing the tests sometime later when I have more time.

**Pull request closed without merging**
