### PR TITLE
Final draft style character autocompletion for dialogues

### PR DESCRIPTION
**Pull request by rickschubert**
The industry standard software Final Draft has a very useful feature when writing dialogue: when jumping to a new line, it automatically suggests the character that spoke before the previous one. That way, when we have a dialogue between two characters MARY and TOBY, Final Draft knows pretty precisely that after TOBY spoke, we will probably want to write another line where MARY replies.

Here is a video which shows how this works in Final Draft: http://recordit.co/M68funBX2U

This pull requests introduces a feature which aims to emulate this by using autocompletes. A video showing how this looks: http://recordit.co/ehGmSTJAAW

### CODE REVIEW

**Comment by rickschubert** [comment]
Edit: I added a video to the description which shows how the feature looks with this pull request (http://recordit.co/ehGmSTJAAW).

**Comment by rickschubert** [comment]
@piersdeseilligny What can I do to help get this pull request merged? Is there anything I should address?

**Comment by piersdeseilligny** [comment]
@rickschubert sorry but I've been on holiday for the last week and haven't been able to merge it. I'm getting back tonight and will look at doing so over the weekend.

**Comment by piersdeseilligny** [comment]
@rickschubert I've played around a little bit with your pr, it's a pretty neat feature! Everything seems fine, the only problem i've been able to find is that `potentialCharacterLine` in `utils.ts` needs to be sanitized in order to:

* Remove the potentially leading `@` from forced character elements, e.g. `@McCLANE`

* Remove character extensions at the end, e.g. `JOHN (on the radio)`

* Remove dual-dialogue indicating carets, e.g. `JOHN ^`

Removing the leading `@` can be done pretty trivially, and removing the character extensions + caret can be done with something like `potentialCharacterLine.replace(/(\([A-z0-9 '\-.()]+\))*(\s*\^*)?$/, "");`.

However for this to work correctly, the characters in `fountainDocProps.characters` need to have the character extension stripped from them too, which can be done by adding a regex `.replace` around [line 471](`https://github.com/piersdeseilligny/betterfountain/blob/master/src/extension.ts#L471`) of `extension.ts` (although no need to also remove the caret, as it wouldn't be included in `token.text`)

**Comment by rickschubert** [comment]
Hi @piersdeseilligny - I thought you might have not gotten e-mail notifications without me mentioning you with a tag. Thank you for the quick review, I will take a look at your comments!

**Comment by rickschubert** [comment]
I have now added support for the special cases you mentioned. Great point @piersdeseilligny , I wasn't aware of these special cases in fountain yet. You can see a video showing the new features here: http://recordit.co/1dNICiK9R7

**Comment by piersdeseilligny** [comment]
@rickschubert This feature is now live in the marketplace, however I changed your implementation quite a bit:

The autocomplete list is now determined based off the [`getCharactersWhoSpokeBeforeLast()`](https://github.com/piersdeseilligny/betterfountain/blob/master/src/utils.ts#L24) function, which iterates through all tokens in the parsed document between the current line and the beginning of the scene. If it runs into a character token, it adds it to the autocomplete list. This means that in the following example:

````
BOB
Hi

ALICE
Hi

JOHN
Hi
````

The autocomplete options will be, in the following order: `ALICE`,`BOB`.

This also ensures that the autocomplete results will be fully consistent with the way the extension understands characters in the screenplay, as they are based off the token array created by the [parser](https://github.com/piersdeseilligny/betterfountain/blob/master/src/afterwriting-parser.ts) used by the other various components of the extension.

Performance is also excellent. The autocomplete list is obtained in 0.8ms to 1.1ms for the ENTIRETY of the screenplay for Aliens, with all scene headings removed (so the parser understands it as a single scene). And that's an incredibly unrealistic usage scenario. In any reasonable context it takes about 0.01ms.

**Comment by rickschubert** [comment]
@piersdeseilligny Thank you very much for implementing this feature, this is amazing! Thank you also for adding onto it, that is highly appreciated. I will let you know should I see anything peculiar, but from what I have seen so far so since using the latest update, it seems to be working well.

Thank you also for the great extension in general - writing a screenplay is a lot of fun with this.

**Pull request merged**
