### PR TITLE
Highlight characters

### PR DESCRIPTION
**Pull request by rnwzd**
Done:
- Export and highlight multiple characters
- Build pdf with ctrl+shift+b
- CI/CD (on Linux at least) with f5, bounded to save on ${fountain_file_name}.pdf and open it

TO DO:
- Check the code and its style
- Give the option to have multiple colours (maybe we can pick a random colour based on the character's name)
- Give the option to highlight characters in another way for those who are printing in black and white

### CODE REVIEW

**Comment by daryluren** [comment]
Hi @rnwzd  
Nice work so far
I was playing around out of curiosity and discovered it doesn't highlight on the pdf if dialogue numbers is turned on.
Cheers

**Comment by daryluren** [comment]
@rnwzd good fixes.
Personally I'm in favour of the colour idea. Even with Piers designing the sidecar/advanced print options, it would be nice to have a function that turns a word (character name) into a colour. (and I could use something like that elsewhere :P ) When the advanced print options are finished it could still be used to pre-fill the character colours.

**Comment by piersdeseilligny** [comment]
Amazing work @rnwzd ! I just have two quick thoughts:

1. Do we think it's an issue that the hashing function will highlight anagrams with the same colour? for example `ALICE` and `CELIA`, or `ANDREW` and `WARDEN`. I don't think there's a particularly high chance of this occurring very often, but it may be something to keep in mind? If there's no easy fix, I guess we can wait until we have a better UI to tackle it

2. Should we only highlight the character name, or should all of their dialogue be highlighted?

**Comment by rnwzd** [comment]
As for now, I have chosen to have all the colors with the same value and
same saturation,
because if they are too bright or dark, either we cannot see the
highlighter or we cannot read the text.
So the only remaining variable is hue, but we cannot have values that are
too close, since we would not  be able to distinguish them.
So now we only have 32 different colors, which I think is enough for any
reasonable script.
Why would someone highlight all the characters anyway?

I have implemented a simple hash function, but since we only have 32
possible values it is likely that it may conflict.
The safest way would be that of parsing all characters and then assigning
them a color.
I did not do that because the highlight function does not have access to
the list of characters .
It must be refactored anyway.

As for question number 2 I think that we can safely have an entry in the
settings for the users to choose from.


Il giorno lun 9 nov 2020 alle ore 16:04 Piers Deseilligny <
notifications@github.com> ha scritto:

**Comment by daryluren** [comment]
The beauty of this is that multiple scripts for the same tv show will give the characters the same colour every time. And even with a more chaotic hash function, there will be hash collisions.

@rnwzd another bug, Statistics errors as it sends a null expcfg to generate()

**Pull request merged**
