### PR TITLE
Outline icons

### PR DESCRIPTION
**Pull request by daryluren**
**Functional stuff:**

Synopses now show on the Outline tree in the right order (they used to all stay at the bottom of their group).
Notes are now visible on the Outline tree, toggle-able.

**Outline tree icons and design choices:**

Sections are hashes, just like in the syntax. Three colours used, which cycle, copied from the 'F' in the betterfountain logo.
Scenes are dots, just like in the syntax. Blue because Scenes are blue in the betterfountain syntax highlighting in Dark+.
Synopses are equals signs, just like in the syntax. Green because comments are green in most syntax highlighting, including betterfountain in Dark+.
Notes are yellow sticky-note-like icon... I tried using '[[' like in the syntax but it just didn't work out lol
Angles used in the '#' and '=' based on the shape of the 'F' in the betterfountain logo.

I haven't made dark/light versions. It looks pretty good in all the pre-packaged colour themes anyway.

**Doubts:**

item.iconPath = __filename + '/../../../assets/scene.svg'; //doesn't seem like the most elegant way to reference assets. What I've found online is confusing but apparently this should still work when published.

### CODE REVIEW

**Comment by daryluren** [comment]
image

**Comment by viegasfh** [comment]
Really nice feature!

I hope this gets merged into the main repository soon.

**Comment by piersdeseilligny** [comment]
Sorry for taking so long to get around merging this, September has been very busy for me. I'm just going to do a few adjustments, so that the icons are more in line with [vscode-codicons](https://github.com/microsoft/vscode-codicons) and i'il merge asap

**Comment by piersdeseilligny** [comment]
image

@daryluren what do you think of these changes?

**Comment by viegasfh** [comment]
I liked both, but to be honest I like @daryluren 's equal sign better. Isn't it possible to replicate that? I don't deslike your proposal. Both look good to me.

Well done, guys!

**Comment by piersdeseilligny** [comment]
image
image


@viegasfh  how about this?

**Comment by viegasfh** [comment]
I like it. It looks great to me.

**Comment by piersdeseilligny** [comment]
Awesome, i'il publish it to the marketplace very soon :)

another change I've made is that the gradient for sections no longer repeats: it goes up to section5, and then just keeps the same color (why would anyone have even a depth of 5 anyway?):

image

**Comment by viegasfh** [comment]
Looking great! Look forward for the update.

I have never used more than a 4 level deep. But you never know. I think someone, or even me, may find a way of going 5 levels deep.

Great job! This plugin is looking really good.

**Comment by daryluren** [comment]
> @daryluren what do you think of these changes?
@piersdeseilligny 

I deliberately made the hashes and equals match the angles in the bf "F" icon so that you would be more willing to accept them 😅  but yeah it still looks nice. The grey Note looks better than my yellow one.

👍

**Pull request merged**
