### PR TITLE
Automatically numbering scenes

### PR DESCRIPTION
**Pull request by rickschubert**
This pull request adds a new command "Number scenes" which automatically numbers all scenes in a screenplay. It also adds a setting which would make it possible that the scenes are being numbered automatically each time the user saves the document.

(@piersdeseilligny Please forget about the previous comment I had added here - I simply forgot to commit the change I made which submits the "number scenes" command. So this pull request is all working now.)

### CODE REVIEW

**Comment by rickschubert** [comment]
Here is a short video showcasing the on save functionality: https://recordit.co/dOzr5HqcaK

**Comment by piersdeseilligny** [comment]
Looks good! I'm just going to make a few changes, and i'ill merge it in for the next release.

**Comment by rickschubert** [comment]
Great, thank you!

**Comment by rickschubert** [comment]
Any chance this will ever be released?

**Comment by piersdeseilligny** [comment]
I'm really busy right now, but i'il have time to work on it in a month or two :/

**Comment by piersdeseilligny** [comment]
I've manually merged this pull request with commit 87c6fae8af71a59c0d60e0fe7b7c5ed0688c3a2f, as there have been quite a few structural changes to the extension since it was made and it was easier than resolving the conflicts. This feature will be in the next release. Sorry for taking so long to deal with this!

**Comment by rickschubert** [comment]
Oh wow, this is a big honour to me, thank you very much!

**Comment by piersdeseilligny** [comment]
@rickschubert no worries! it's included as part of 1.5.0, which has just gone live in the marketplace.

**Pull request closed without merging**
