### PR TITLE
Added configuration entry for CONT'D and MORE

### PR DESCRIPTION
**Pull request by rnwzd**
I added two custom entries in configuration to change CONT'D and MORE to something else, for non-english-speaking people.

### CODE REVIEW

**Comment by rnwzd** [comment]
Hi,
I am a physicist turned film maker. I find your extension really useful and I might want to work on it in my spare time.

Cheers
rnwzd

**Comment by piersdeseilligny** [comment]
Thanks for the PR! And it makes me really happy you find the extension useful :) I just did a couple changes to the description and moved both entries to the `fountain.pdf` namespace, rather than `fountain.general`.

**Comment by rnwzd** [comment]
Sure, thanks for correcting my English.
Is there a way I can communicate to you more directly, to propose and discuss development roadmap and design?

**Comment by piersdeseilligny** [comment]
Sure! Either by [email](mailto:piers.deseilligny@outlook.com) or on [discord](https://discord.gg/QBm7tKQ) where there's a (very) small community of those of us who are involved in developing betterfountain :)

**Pull request merged**
