### PR TITLE
Take Number setting

### PR DESCRIPTION
**Pull request by segreeeen**
o added ability to show take numbers in front of character names in preview and pdf as a settings checkbox (default false)
o upgraded engine in package.json to 1.26.0
o preview is now reloaded automatically when settings are changed

### CODE REVIEW

**Comment by piersdeseilligny** [comment]
Thanks for the pull request! but before I merge it, is "take numbers" the best way to describe this feature? I've never heard of screenplays with these, what exactly is their purpose?

**Comment by segreeeen** [comment]
Hello,
I come from hobby audioplay writing, where we refer to a line of a character as a "take". We often use that unique number of a take to refer to the line when takes of multiple voiceactors are mixed independently from each other into one final audoplay. The term is also used in the movie industry: https://en.m.wikipedia.org/wiki/Take
Otherwise we can also call it anything else. What are you thinking of? Maybe something like Character Numbering? You sure know best how to make this fit in the established nomenclature :).

**Comment by piersdeseilligny** [comment]
Good to know :) to avoid confusion with "take" in the way that it's traditionally referred to in film, maybe "Dialogue Numbering" would be better?

**Comment by segreeeen** [comment]
Sure, sounds good.

**Review by piersdeseilligny — CHANGES_REQUESTED** [review]
Could you just refactor the pull request by replacing "take numbers" with "dialogue numbering"?

**Comment by segreeeen** [comment]
Done :)

**Review by piersdeseilligny — APPROVED** [review]

**Comment by piersdeseilligny** [comment]
@segreeeen In addition to showing on the preview and PDF, I've added editor decorations, so that the dialogue numbers also show up in the editor, as such:

image

It's live in the marketplace right now, as part of betterfountain 1.5.0

**Comment by segreeeen** [comment]
Grat idea! Thanks - I wasn't sure if that's even possible. Nice addition.

**Pull request merged**
